function recon = Griswold_norm(yn,wfull,cmap);
% normalization proposed in the abstract by Griswold et al.

% Reconstruction of array data and computation of coil sensitivities based 
% on: a) Adaptive Reconstruction of MRI array data, Walsh et al. Magn Reson
% Med. 2000; 43(5):682-90 and b) Griswold et al. ISMRM 2002: 2410
%-------------------------------------------------------------------------
%	Input:
%	yn: array data to be combined [ny, nx, nc], generated by the 
%	wfull
%
%	Output:
%	recon: reconstructed image [ny, nx].
%	cmap: estimated coil sensitivity maps [ny, nx, nc].
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------

recon=zeros(ny,nx);

% Interpolation of cmap upto the full resolution
recon=squeeze(sum(wfull.*yn));   %Combine coil signals. 
recon=recon.*squeeze(sum(abs(cmap))).^2; 

cmap=permute(cmap,[2,3,1]);
